apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoperson
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 40
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    initialDelay: 40
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://syfoperson.intern.dev.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: dev-gcp
    outbound:
      external:
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "syfo-tilgangskontroll.dev-fss-pub.nais.io"
      rules:
        - application: syfoperson-redis
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: skjermede-personer-pip
          namespace: nom
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  envFrom:
    - secret: syfoperson-redis-password
  env:
    - name: KRR_CLIENT_ID
      value: "dev-gcp.team-rocket.digdir-krr-proxy"
    - name: KRR_URL
      value: "http://digdir-krr-proxy.team-rocket"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: REDIS_HOST
      value: "syfoperson-redis.teamsykefravr.svc.cluster.local"
    - name: SKJERMEDEPERSONERPIP_CLIENT_ID
      value: "dev-gcp.nom.skjermede-personer-pip"
    - name: SKJERMEDEPERSONERPIP_URL
      value: "http://skjermede-personer-pip.nom"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.dev-fss-pub.nais.io"
