apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoperson
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfoperson/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /syfoperson/internal/isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfoperson/internal/prometheus
  ingresses:
    - "https://syfoperson.intern.nav.no"
    - "https://syfoperson.prod-fss-pub.nais.io"
    - "https://syfoperson.nais.adeo.no"
  vault:
    enabled: true
    paths:
      - kvPath: "/serviceuser/data/prod/srvsyfoperson"
        mountPath: "/secrets/serviceuser/syfoperson"
      - kvPath: "/kv/prod/fss/syfoperson/default"
        mountPath: "/var/run/secrets/nais.io/vault"
  env:
    - name: APP_NAME
      value: "syfoperson"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_DISCOVERYURL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_ACCEPTEDAUDIENCE
      value: 9b4e07a3-4f4c-4bab-b866-87f62dff480d
    - name: DKIF_URL
      value: https://dkif.nais.adeo.no
    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.adeo.no
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.adeo.no/syfo-tilgangskontroll/api/tilgang
