apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoperson
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /syfoperson/internal/isAlive
    initialDelay: 40
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /syfoperson/internal/isReady
    initialDelay: 40
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 768Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfoperson/internal/prometheus
  ingresses:
    - "https://syfoperson.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: prod-fss
    outbound:
      external:
        - host: "isproxy.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "syfo-tilgangskontroll.dev-fss-pub.nais.io"
      rules:
        - application: syfoperson-redis
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://syfoperson.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  env:
    - name: ISPROXY_CLIENT_ID
      value: "prod-fss.teamsykefravr.isproxy"
    - name: ISPROXY_URL
      value: "https://isproxy.intern.nav.no"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: TILGANGSKONTROLLAPI_URL
      value: "https://syfo-tilgangskontroll.prod-fss-pub.nais.io/syfo-tilgangskontroll/api/tilgang"
