apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoperson
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 40
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    initialDelay: 40
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://syfoperson.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: finnfastlege
        - application: syfomodiaperson
        - application: syfomoteoversikt
        - application: syfooversikt
    outbound:
      external:
        - host: "pdl-api.prod-fss-pub.nais.io"
      rules:
        - application: syfoperson-redis
        - application: istilgangskontroll
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: skjermede-personer-pip
          namespace: nom
        - application: kodeverk-api
          namespace: team-rocket
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  envFrom:
    - secret: syfoperson-redis-password
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: KRR_CLIENT_ID
      value: "prod-gcp.team-rocket.digdir-krr-proxy"
    - name: KRR_URL
      value: "http://digdir-krr-proxy.team-rocket"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: REDIS_HOST
      value: "syfoperson-redis.teamsykefravr.svc.cluster.local"
    - name: SKJERMEDEPERSONERPIP_CLIENT_ID
      value: "prod-gcp.nom.skjermede-personer-pip"
    - name: SKJERMEDEPERSONERPIP_URL
      value: "http://skjermede-personer-pip.nom"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: KODEVERK_CLIENT_ID
      value: "prod-gcp.team-rocket.kodeverk-api"
    - name: KODEVERK_URL
      value: "http://kodeverk-api.team-rocket"
