apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoperson
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfoperson/internal/isAlive
    initialDelay: 40
    timeout: 1
    periodSeconds: 20
    failureThreshold: 3
  readiness:
    path: /syfoperson/internal/isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfoperson/internal/prometheus
  ingresses:
    - "https://syfoperson.dev.intern.nav.no"
    - "https://syfoperson.dev-fss-pub.nais.io"
    - "https://syfoperson.nais.preprod.local"
  accessPolicy:
    inbound:
      rules:
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: dev-fss
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://syfoperson.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/serviceuser/data/dev/srvsyfoperson"
        mountPath: "/secrets/serviceuser/syfoperson"
      - kvPath: "/kv/preprod/fss/syfoperson/default"
        mountPath: "/var/run/secrets/nais.io/vault"
  env:
    - name: APP_NAME
      value: "syfoperson"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "32e36aa5-1d12-452a-9b1e-9f3f557cbb4d"
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDERAAD_DISCOVERYURL
      value: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration"
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_DISCOVERYURL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_ACCEPTEDAUDIENCE
      value: 38e07d31-659d-4595-939a-f18dce3446c5
    - name: DKIF_URL
      value: https://dkif.nais.preprod.local
    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.preprod.local
    - name: SYFOSYKETILFELLE_URL
      value: "https://syfosyketilfelle.nais.preprod.local"
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll/api/tilgang
