apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoperson
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfoperson/internal/isAlive
    initialDelay: 40
    timeout: 1
    periodSeconds: 20
    failureThreshold: 3
  readiness:
    path: /syfoperson/internal/isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 768Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfoperson/internal/prometheus
  ingresses:
    - "https://syfoperson.dev.intern.nav.no"
    - "https://syfoperson.dev-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: dev-fss
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://syfoperson.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/serviceuser/data/dev/srvsyfoperson"
        mountPath: "/secrets/serviceuser/syfoperson"
      - kvPath: "/kv/preprod/fss/syfoperson/default"
        mountPath: "/var/run/secrets/nais.io/vault"
  env:
    - name: APP_NAME
      value: "syfoperson"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: ISPROXY_CLIENT_ID
      value: "dev-fss.teamsykefravr.isproxy"
    - name: ISPROXY_URL
      value: "https://isproxy.dev.intern.nav.no"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev.intern.nav.no/graphql"
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.preprod.local
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll/api/tilgang
