spring:
  cache.type: redis
  redis:
    host: syfoperson-redis
    port: 6379
    password: ${redis.password}

no.nav.security.jwt:
  issuer:
    veilederaad:
      discoveryurl: ${azure.app.well.known.url}
      accepted_audience: ${azure.app.client.id}
      cookiename: ID_token

logging.config: classpath:logback-spring.xml

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

server:
  servlet:
    context-path: /syfoperson
