no.nav.security.oidc:
  issuers: veileder
  issuer:
    veileder:
      discoveryurl: <SETTES FRA FASIT>
      accepted_audience: <SETTES FRA FASIT>
      cookie_name: isso-idtoken

logging.config: classpath:logback-spring.xml

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

server:
  servlet:
    context-path: /syfoperson
