name: Security 
on: 
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor 
          args: --project-name=${{ github.repository }}